server:
  port: 8080
  servlet:
    context-path: /api/agent

app:
  chat:
    history-limit: 20
    rag:
      percentage: 30
      top-k: 100
  configPath: ${CONFIG_PATH:classpath:models}

spring:
  application:
    name: agent
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ai}
    username: ${DATABASE_USERNAME:aiuser}
    password: ${DATABASE_PASSWORD:aipass}
  jpa:
    open-in-view: false
  ai:
    model:
      chat: none
      embedding: none
      image: none
      moderation: none
      audio:
        speech: none
        transcription: none
    vectorstore:
      pgvector:
        table-name: documents

springdoc:
  api-docs:
    path: /api-docs
