server:
  port: 8080
  servlet:
    context-path: /api/agent

app:
  chat:
    history-limit: 20
    rag:
      percentage: 30
      top-k: 100
  embedding:
    provider: ${EMBEDDING_PROVIDER:openai}
    dimensions: ${EMBEDDING_DIMENSIONS:1536}
    openai:
      enabled: ${OPENAI_EMBEDDING_ENABLED:true}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      api-key: ${OPENAI_API_KEY:API_KEY}
      model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
  configPath: ${CONFIG_PATH:classpath:models}

spring:
  application:
    name: agent
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ai}
    username: ${DATABASE_USERNAME:aiuser}
    password: ${DATABASE_PASSWORD:aipass}
  jpa:
    open-in-view: false
  ai:
    vectorstore:
      pgvector:
        table-name: documents
        dimensions: ${app.embedding.dimensions}
    openai:
      base-url: ${app.embedding.openai.base-url}
      api-key: ${app.embedding.openai.api-key}
      embedding:
        enabled: ${app.embedding.openai.enabled}
        options:
          model: ${app.embedding.openai.model}
          dimensions: ${app.embedding.dimensions}
      chat:
        enabled: false

springdoc:
  api-docs:
    path: /api-docs
